### ISSUE TITLE
2020년 9월 1주차 문제

### ISSUE THREAD

**Issue by gkm2019** [SSAFY-Problem-Solving/Problem-Solving#4]
* [puyo puyo](https://www.acmicpc.net/problem/11559)
* [토마토](https://www.acmicpc.net/problem/7569)

이슈 `#4` 입니다. `commit`하실 때, `(#4)`라고 작성해 주세요!!!

**Comment by ber01** [comment]
~~~java
for (int i = 0; i < 12; i++) {
    String line = br.readLine();
    for (int j = 0; j < 6; j++) {
        map[i][j] = line.charAt(j);
    }
}
~~~

~~~java
for (int i = 0; i < 12; i++) {
    map[i] = br.readLine().toCharArray();
}
~~~

아래가 빠를 줄 알았는데 길이가 길어지면 길어질수록 위에가 훠어어어어어얼씬 더 빠릅니다!!
length가 `2억` 일 때, 위가 아래보다 `56`배 빠름
